spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/test
    username: sa
    password:
    driver-class-name: org.h2.Driver



  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true

  thymeleaf:
    mode: LEGACYHTML5
    cache: false


logging:
  level:
    org.hibernate.SQL: debug

