spring:
  datasource:
    url: jdbc:mysql://localhost:3306/jpashop
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
#        show_sql: true
        format_sql: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher


decorator:
  datasource:
    p6spy:
      enable-logging: true

logging:
  level:
    org.hibernate.SQL: debug

server:
  port: ${PORT:8080}
  error:
    whitelabel:
      enabled: false