spring:
  application:
    name: bankapp

  datasource:
    url: jdbc:mysql://localhost:3306/bank
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

logging:
  level:
    org.springframework.jdbc.datasource.init: DEBUG