spring:
  datasource:
    username: root
    password:
    url: jdbc:mysql://localhost:3306/eazybank?useSSL=false&serverTimezone=UTC
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
logging:
  level:
    org:
      springframework:
        security:
          web:
            FilterChainProxy: DEBUG
