spring:
  datasource:
    url: jdbc:mysql://localhost:3306/shop?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10

  jpa:
    database: mysql
    show-sql: true

logging:
  level:
    root: info
    com.example: debug
    org.springframework.web: debug