spring:
  datasource:
    url: jdbc:mysql://localhost:3306/example
    username: root
    password:
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  data:
    redis:
      host: localhost
      port: 6379
      database: 0